#!/usr/bin/env python3
"""Render sdks/c/include/seyd.h as a Starlight page (PLAN.md §2.8).

The header is generated by cbindgen from packages/seyd-ffi, so its `/** */`
comments are the Rust `///` comments: the reference is written once, in the
source, and this script only lays it out. Every top-level item is emitted, in
header order, grouped by kind; a function or struct field without a doc
comment is rendered with an empty description, so gaps are visible on the
page rather than silently dropped.

    gen-c-reference.py [--out FILE]      # default: web/docs/src/content/docs/reference/c.md
"""
import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HEADER = ROOT / "sdks/c/include/seyd.h"
DEFAULT_OUT = ROOT / "web/docs/src/content/docs/reference/c.md"


def clean_doc(block: str) -> str:
    """Strip the comment furniture and return Markdown-ready text."""
    lines = []
    for raw in block.splitlines():
        line = raw.strip()
        if line.startswith("/**"):
            line = line[3:]
        if line.endswith("*/"):
            line = line[:-2]
        line = re.sub(r"^\*\s?", "", line.strip())
        lines.append(line)
    text = "\n".join(lines).strip()
    # Rustdoc's `# Safety` heading becomes a labelled paragraph; H1s in a page body are wrong.
    text = re.sub(r"^# Safety\s*$", "**Safety.**", text, flags=re.M)
    text = re.sub(r"\[`([^`]+)`\]", r"`\1`", text)  # rustdoc intra-links → plain code
    return text


class Item:
    def __init__(self, kind: str, name: str, decl: str, doc: str, members=None):
        self.kind, self.name, self.decl, self.doc, self.members = kind, name, decl, doc, members or []


def parse(text: str) -> list[Item]:
    items: list[Item] = []
    i, n = 0, len(text)
    pending_doc = ""
    while i < n:
        m = re.compile(r"/\*\*(.*?)\*/", re.S).match(text, i)
        if m:
            pending_doc = clean_doc(m.group(0))
            i = m.end()
            continue
        m = re.compile(r"/\*.*?\*/", re.S).match(text, i)  # non-doc comment
        if m:
            i = m.end()
            continue
        if text.startswith("#define SEYD_", i):
            end = text.index("\n", i)
            decl = text[i:end].strip()
            name = decl.split()[1]
            if name != "SEYD_H":  # the include guard is not API
                items.append(Item("constant", name, decl, pending_doc))
            pending_doc = ""
            i = end + 1
            continue
        if text.startswith("typedef enum", i) or text.startswith("typedef struct", i):
            brace = text.find("{", i)
            semi = text.find(";", i)
            if brace == -1 or (semi != -1 and semi < brace):  # forward declaration: typedef struct x x;
                decl = text[i:semi + 1]
                name = decl.split()[-1].rstrip(";")
                items.append(Item("opaque", name, decl.strip(), pending_doc))
                pending_doc = ""
                i = semi + 1
                continue
            depth, j = 0, brace
            while True:
                if text[j] == "{":
                    depth += 1
                elif text[j] == "}":
                    depth -= 1
                    if depth == 0:
                        break
                j += 1
            semi = text.index(";", j)
            decl = text[i:semi + 1]
            name = decl[j - i + 1:].strip().rstrip(";").strip()
            kind = "enum" if text.startswith("typedef enum", i) else "struct"
            items.append(Item(kind, name, decl, pending_doc, parse_members(text[brace + 1:j], kind)))
            pending_doc = ""
            i = semi + 1
            continue
        m = re.compile(r"[A-Za-z_][\w \*]*?\b(seyd_[a-z_0-9]+)\s*\(", re.S).match(text, i)
        if m and not text[i:m.start(1)].strip().startswith("("):
            semi = text.index(";", i)
            decl = re.sub(r"\s+", " ", text[i:semi + 1]).strip()
            items.append(Item("function", m.group(1), decl, pending_doc))
            pending_doc = ""
            i = semi + 1
            continue
        i = text.find("\n", i)
        if i == -1:
            break
        i += 1
    return items


def parse_members(body: str, kind: str) -> list[tuple[str, str]]:
    """(declaration, doc) per member, in order; function-pointer members included."""
    members, doc, i = [], "", 0
    while i < len(body):
        m = re.compile(r"\s*/\*\*(.*?)\*/", re.S).match(body, i)
        if m:
            doc = clean_doc(m.group(0))
            i = m.end()
            continue
        m = re.compile(r"\s*/\*.*?\*/", re.S).match(body, i)
        if m:
            i = m.end()
            continue
        end = body.find("," if kind == "enum" else ";", i)
        if end == -1:
            chunk = body[i:].strip()
            i = len(body)
        else:
            chunk = body[i:end].strip()
            i = end + 1
        if chunk:
            members.append((re.sub(r"\s+", " ", chunk), doc))
            doc = ""
    return members


def render(items: list[Item]) -> str:
    out = [
        "---",
        "title: C ABI (seyd.h)",
        "description: Every symbol of the Seyd C ABI, rendered from the generated header.",
        "---",
        "",
        "Generated from `sdks/c/include/seyd.h`, which cbindgen produces from `packages/seyd-ffi`;",
        "the descriptions are the Rust doc comments (ADR 0004). Lifecycle:",
        "`seyd_agent_create` → `seyd_channel_add` (once per channel) → `seyd_agent_start` →",
        "`seyd_push_frame` / `seyd_push_message` → `seyd_agent_stop` → `seyd_agent_destroy`.",
        "Callbacks arrive on one dedicated Seyd thread and must not block; `seyd_push_*` never",
        "blocks and may be called from any thread. See [A robot in C](/docs/robot/c/) for the guide.",
        "",
    ]
    groups = [("Constants", "constant"), ("Enumerations", "enum"), ("Structs", "struct"), ("Opaque handles", "opaque"), ("Functions", "function")]
    for title, kind in groups:
        chosen = [it for it in items if it.kind == kind]
        if not chosen:
            continue
        out += [f"## {title}", ""]
        for it in chosen:
            out += [f"### `{it.name}`", ""]
            if it.doc:
                out += [it.doc, ""]
            if kind in ("enum", "struct"):
                out += ["```c", it.decl, "```", ""]
                if it.members:
                    label = "Value" if kind == "enum" else "Field"
                    out += [f"| {label} | Meaning |", "|---|---|"]
                    for decl, doc in it.members:
                        name = member_name(decl, kind)
                        out.append(f"| `{name}` | {doc.replace(chr(10), ' ').replace('|', '\\|')} |")
                    out.append("")
            else:
                out += ["```c", it.decl, "```", ""]
    return "\n".join(out)


def member_name(decl: str, kind: str) -> str:
    if kind == "enum":
        return decl.split("=")[0].strip()
    m = re.search(r"\(\*\s*(\w+)\s*\)", decl)  # function pointer
    if m:
        return m.group(1)
    return decl.split()[-1].lstrip("*")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = ap.parse_args()
    items = parse(HEADER.read_text())
    functions = [it for it in items if it.kind == "function"]
    if not functions:
        sys.exit("gen-c-reference: no functions found in the header; parser broken?")
    undocumented = [it.name for it in items if it.kind == "function" and not it.doc]
    if undocumented:
        print(f"gen-c-reference: undocumented functions: {undocumented}", file=sys.stderr)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(items))
    print(f"gen-c-reference: {len(items)} items ({len(functions)} functions) → {args.out.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
