#!/usr/bin/env python3
"""Keep the integration skill (skills/seyd/) tied to the code (PLAN.md §2.8).

The skill is the document a third-party developer hands their coding agent
("integrate my robot with Seyd"). Its prose is written by hand; two of its
references are generated here from the code, and `--check` fails the docs
build when the hand-written part has gone stale in a way a script can see:

  * `references/seydd-config.md` and `references/qos-profiles.md` are
    rendered by gen-seydd-config.py and gen-qos-profiles.py and checked in,
    like seyd.h: `--check` regenerates them and diffs.
  * Every repository path the skill names in backticks must exist.
  * Every `/docs/…` route the skill names must be a page of web/docs.
  * Every public surface below must be mentioned somewhere in the skill:
    the C ABI's functions and callbacks, the Python Agent's methods and
    handlers, <seyd-video>'s observed attributes, SeydSession's events and
    failure reasons, the Rust AgentEvent variants, the daemon's
    publisher-control message types and the <seyd-connect-error> failure
    classes. Add a function, attribute or event and the build fails until
    the skill says what an integrator does with it.

    gen-skill.py            # (re)generate the two references
    gen-skill.py --check    # verify; exit 1 with a list of what is stale
"""
import argparse
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SKILL = ROOT / "skills/seyd"
TOOLS = ROOT / "tools/docs"
DOCS_CONTENT = ROOT / "web/docs/src/content/docs"

GENERATED = {
    "references/seydd-config.md": "gen-seydd-config.py",
    "references/qos-profiles.md": "gen-qos-profiles.py",
}

# Route prefixes that exist only in the built site (not under src/content/docs).
BUILT_ROUTE_PREFIXES = ("reference/js/", "rust/")


def render(script: str) -> str:
    """Run a docs generator into a temp file and return its output, marked as generated."""
    # Inside the repo: the generators print the output path relative to it.
    with tempfile.NamedTemporaryFile(suffix=".md", prefix=".gen-", dir=SKILL, delete=False) as tmp:
        out = Path(tmp.name)
    try:
        subprocess.run([sys.executable, str(TOOLS / script), "--out", str(out)], check=True, cwd=ROOT, stdout=subprocess.DEVNULL)
        text = out.read_text()
    finally:
        out.unlink(missing_ok=True)
    note = f"<!-- Generated by tools/docs/gen-skill.py via {script}. Do not edit; regenerate. -->\n"
    # Keep the front matter first, so the note does not break it.
    if text.startswith("---\n"):
        end = text.index("\n---\n", 4) + len("\n---\n")
        return text[:end] + "\n" + note + text[end:]
    return note + text


def skill_text() -> str:
    return "\n".join(p.read_text() for p in sorted(SKILL.rglob("*.md")))


def check_generated() -> list[str]:
    problems = []
    for rel, script in GENERATED.items():
        path = SKILL / rel
        if not path.exists():
            problems.append(f"{rel}: missing; run tools/docs/gen-skill.py")
        elif path.read_text() != render(script):
            problems.append(f"{rel}: stale; run tools/docs/gen-skill.py")
    return problems


def check_paths(text: str) -> list[str]:
    """Every backticked repository path must exist (a trailing `/` means a directory)."""
    problems = []
    for m in sorted(set(re.findall(r"`((?:sdks|packages|examples|tools|docs|web|cloud|sim)/[\w./+-]+)`", text))):
        if not (ROOT / m.rstrip("/")).exists():
            problems.append(f"path `{m}` does not exist in the repository")
    return problems


def check_routes(text: str) -> list[str]:
    """Every `/docs/a/b/` route must be a page under web/docs/src/content/docs (after generate)."""
    problems = []
    for route in sorted(set(re.findall(r"(?<![\w.])/docs/([\w/-]+)/", text))):
        if route.startswith(BUILT_ROUTE_PREFIXES):
            continue
        candidates = [DOCS_CONTENT / f"{route}.md", DOCS_CONTENT / f"{route}.mdx", DOCS_CONTENT / route / "index.mdx", DOCS_CONTENT / route / "index.md"]
        if not any(c.exists() for c in candidates):
            problems.append(f"route /docs/{route}/ has no page under web/docs/src/content/docs")
    return problems


def surfaces() -> dict[str, list[str]]:
    """The public names the skill must mention, read from the code."""
    header = (ROOT / "sdks/c/include/seyd.h").read_text()
    c_functions = sorted(set(re.findall(r"\b(seyd_[a-z0-9_]+)\s*\(", header)))
    cb_block = re.search(r"typedef struct seyd_callbacks \{(.*?)\} seyd_callbacks;", header, re.S).group(1)
    c_callbacks = re.findall(r"\(\*(on_[a-z_]+)\)", cb_block)

    agent_py = (ROOT / "sdks/python/seyd/agent.py").read_text()
    cls = agent_py[agent_py.index("class Agent:"):]
    py_methods = sorted(set(re.findall(r"^    def ([a-z][a-z_]*)\(", cls, re.M)))
    py_handlers = sorted(set(re.findall(r"self\.(on_[a-z_]+):", cls)))

    video_ts = (ROOT / "sdks/js/web/src/seyd-video.ts").read_text()
    attrs = re.findall(r"'([a-z-]+)'", re.search(r"observedAttributes = \[(.*?)\]", video_ts).group(1))

    types_ts = (ROOT / "sdks/js/core/src/types.ts").read_text()
    events_block = re.search(r"export interface SessionEvents \{(.*?)\n\}", types_ts, re.S).group(1)
    events = re.findall(r"^\s+'?([a-z-]+)'?:", events_block, re.M)
    reasons = re.findall(r"'([a-z-]+)'", re.search(r"export type FailureReason\s*=(.*?);", types_ts, re.S).group(1))

    agent_rs = (ROOT / "packages/seyd-core/src/agent.rs").read_text()
    variants = re.findall(r"^    ([A-Z][A-Za-z]+)", re.search(r"pub enum AgentEvent \{(.*?)\n\}", agent_rs, re.S).group(1), re.M)

    protocol = (ROOT / "docs/protocol/seydd.md").read_text()
    message_types = sorted(set(re.findall(r'\{"type": "([a-z-]+)"', protocol)))

    error_ts = (ROOT / "sdks/js/web/src/seyd-connect-error.ts").read_text()
    classes = re.findall(r"'([a-z0-9-]+)'", re.search(r"export type FailureClass\s*=\s*(.*?);", error_ts, re.S).group(1))

    return {
        "C function": c_functions,
        "C callback": c_callbacks,
        "Python Agent method": py_methods,
        "Python Agent handler": py_handlers,
        "<seyd-video> attribute": attrs,
        "SeydSession event": events,
        "FailureReason": reasons,
        "AgentEvent variant": variants,
        "publisher-control message type": message_types,
        "FailureClass": classes,
    }


def check_surfaces(text: str) -> list[str]:
    problems = []
    for kind, names in surfaces().items():
        for name in names:
            if not re.search(r"(?<![\w-])" + re.escape(name) + r"(?![\w-])", text):
                problems.append(f"{kind} `{name}` is not mentioned anywhere in skills/seyd/")
    return problems


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="verify instead of generating")
    args = ap.parse_args()

    if not args.check:
        for rel, script in GENERATED.items():
            (SKILL / rel).write_text(render(script))
            print(f"gen-skill: {script} → skills/seyd/{rel}")

    text = skill_text()
    problems = check_generated() + check_paths(text) + check_routes(text) + check_surfaces(text)
    if problems:
        print("skill: skills/seyd/ is out of date:", file=sys.stderr)
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        return 1
    n = sum(len(v) for v in surfaces().values())
    print(f"skill: {n} public surfaces mentioned, every path and route resolves, generated references current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
